on:
  push:
    branches:
      - main
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: bash .github/workflows/build_react.sh
      - run: bash .github/workflows/deploy_to_firebase.sh '${{ secrets.SA_KEY }}'
